import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";

import type {
  Finding,
  OnboardingConceptEvidence,
  OnboardingStoryClaim,
  OnboardingStoryEvidence,
} from "@transferkit/core";

const documentFiles = [
  "README.md",
  "docs/README.md",
  "docs/ABOUT.md",
  "docs/OVERVIEW.md",
] as const;
const starter =
  /(?:nest(?:js)? (?:framework|starter)|starter (?:repository|template|project)|boilerplate|generated by|welcome to|progressive node\.js framework|create-react-app)/iu;
const sensitive =
  /(?:password|secret|api[_-]?key|private[_-]?key|token)\s*[:=]|-----BEGIN|process\.env\.[A-Z_]+\s*=/iu;

export async function discoverOnboardingStoryEvidence(
  directory: string,
  findings: readonly Finding[],
  concepts: OnboardingConceptEvidence,
): Promise<OnboardingStoryEvidence> {
  const claims: OnboardingStoryClaim[] = [];
  const rejectedDescriptions: OnboardingStoryEvidence["rejectedDescriptions"] =
    [];
  const paragraphs: {
    text: string;
    file: string;
    line: number;
    endLine: number;
  }[] = [];
  for (const file of documentFiles) {
    const source = await optionalText(join(directory, file));
    if (!source) continue;
    const genericDocument = starter.test(source.slice(0, 1200));
    for (const match of source.matchAll(
      /`((?:npm (?:run )?(?:start|test)(?:\s+--)?|python3?\s+[\w./-]+\.py)(?:\s+[^`\n]{1,90})?)`/gu,
    )) {
      const command = match[1]!.trim();
      if (genericDocument || sensitive.test(command)) continue;
      claims.push({
        kind: "observation",
        text: `Documented command: ${command}. It has not been run by TransferKit.`,
        basis: "repository-statement",
        evidence: [
          { file, line: source.slice(0, match.index).split(/\r?\n/u).length },
        ],
      });
    }
    if (!genericDocument)
      for (const match of source.matchAll(
        /(?:^|[.!?]\s+)([^.!?\n]{0,180}\b(?:missing|invalid|rejected|error|nonzero|404)\b[^.!?\n]{0,180}[.!?])/gimu,
      )) {
        const statement = match[1]!.trim();
        if (sensitive.test(statement)) continue;
        const line = source
          .slice(0, match.index! + match[0].indexOf(match[1]!))
          .split(/\r?\n/u).length;
        claims.push({
          kind: "observation",
          text: `Documented alternate: ${statement}`,
          basis: "repository-statement",
          evidence: [{ file, line }],
        });
      }
    for (const match of source.matchAll(/\bpython3?\s+([\w./-]+\.py)\b/gu)) {
      const target = match[1]!;
      if (!(await localFile(directory, target))) continue;
      claims.push({
        kind: "entry",
        name: target,
        text: `The documented Python command enters at ${target}.`,
        basis: "repository-statement",
        evidence: [
          { file, line: source.slice(0, match.index).split(/\r?\n/u).length },
          { file: target, line: 1 },
        ],
      });
    }
    const paragraph = projectParagraph(source);
    if (!paragraph) continue;
    const evidence = Array.from(
      { length: paragraph.endLine - paragraph.line + 1 },
      (_, offset) => ({ file, line: paragraph.line + offset }),
    );
    if (starter.test(paragraph.text) || sensitive.test(paragraph.text)) {
      rejectedDescriptions.push({
        text: paragraph.text,
        evidence,
        reason: starter.test(paragraph.text)
          ? "generic starter text"
          : "potentially sensitive text",
      });
      continue;
    }
    paragraphs.push({ ...paragraph, file });
    claims.push({
      kind: "purpose",
      text: paragraph.text,
      basis: "repository-statement",
      evidence,
    });
    const role =
      /\b(command-line tool|CLI|service|library|worker|utility)\b/iu.exec(
        paragraph.text,
      )?.[1];
    if (role)
      claims.push({
        kind: "role",
        text: `The repository describes itself as a ${role}.`,
        basis: "repository-statement",
        evidence,
      });
    for (const sentence of paragraph.text.split(/(?<=[.!?])\s+/u)) {
      if (
        /\b(?:reads?|accepts?|takes?)\b.{0,100}\b(?:file|input|csv|json)/iu.test(
          sentence,
        )
      )
        claims.push({
          kind: "artifact",
          text: sentence,
          basis: "repository-statement",
          evidence,
        });
      if (/\b(?:prints?|writes?|returns?|outputs?|exposes?)\b/iu.test(sentence))
        claims.push({
          kind: "output",
          text: sentence,
          basis: "repository-statement",
          evidence,
        });
    }
  }

  const packageSource = await optionalText(join(directory, "package.json"));
  if (packageSource) {
    try {
      const pkg = JSON.parse(packageSource) as Record<string, unknown>;
      const engines = stringMap(pkg.engines);
      if (engines.node)
        claims.push({
          kind: "observation",
          text: `Declared runtime: Node.js ${engines.node}.`,
          basis: "code-observation",
          evidence: [
            { file: "package.json", line: propertyLine(packageSource, "node") },
          ],
        });
      for (const [name, version] of Object.entries(stringMap(pkg.dependencies))
        .filter(([name]) =>
          /^(?:@nestjs\/core|@nestjs\/typeorm|@nestjs\/bullmq|express|fastify|next|react|typeorm|pg|prisma|bullmq|amqplib|commander|yargs)$/u.test(
            name,
          ),
        )
        .slice(0, 8))
        claims.push({
          kind: "observation",
          text: `Declared runtime dependency: ${name} ${version}.`,
          basis: "code-observation",
          evidence: [
            { file: "package.json", line: propertyLine(packageSource, name) },
          ],
        });
      if (
        typeof pkg.description === "string" &&
        pkg.description.length >= 24 &&
        pkg.description.length <= 250
      ) {
        const evidence = [
          {
            file: "package.json",
            line: propertyLine(packageSource, "description"),
          },
        ];
        if (starter.test(pkg.description) || sensitive.test(pkg.description))
          rejectedDescriptions.push({
            text: pkg.description,
            evidence,
            reason: starter.test(pkg.description)
              ? "generic starter text"
              : "potentially sensitive text",
          });
        else
          claims.push({
            kind: "purpose",
            text: pkg.description,
            basis: "repository-statement",
            evidence,
          });
      }
      const bins =
        typeof pkg.bin === "string" && typeof pkg.name === "string"
          ? { [pkg.name]: pkg.bin }
          : stringMap(pkg.bin);
      for (const [command, file] of Object.entries(bins).slice(0, 8)) {
        if (!(await localFile(directory, file))) continue;
        claims.push({
          kind: "entry",
          name: command,
          text: `The ${command} command enters at ${file}.`,
          basis: "code-observation",
          evidence: [
            {
              file: "package.json",
              line: propertyLine(packageSource, command),
            },
            { file, line: 1 },
          ],
        });
        claims.push({
          kind: "role",
          text: `This package declares the ${command} command.`,
          basis: "code-observation",
          evidence: [
            {
              file: "package.json",
              line: propertyLine(packageSource, command),
            },
          ],
        });
      }
      for (const field of ["main", "module"] as const) {
        const file = pkg[field];
        if (typeof file !== "string" || !(await localFile(directory, file)))
          continue;
        claims.push({
          kind: "entry",
          name: field,
          text: `The package ${field} entry points to ${file}.`,
          basis: "code-observation",
          evidence: [
            { file: "package.json", line: propertyLine(packageSource, field) },
            { file, line: 1 },
          ],
        });
      }
      const exportRoot = object(pkg.exports)["."];
      const exportFile =
        typeof exportRoot === "string"
          ? exportRoot
          : (string(object(exportRoot).default) ??
            string(object(exportRoot).import));
      if (exportFile && (await localFile(directory, exportFile)))
        claims.push({
          kind: "entry",
          name: "public export",
          text: `The package public export points to ${exportFile}.`,
          basis: "code-observation",
          evidence: [
            {
              file: "package.json",
              line: propertyLine(packageSource, "exports"),
            },
            { file: exportFile, line: 1 },
          ],
        });
      const start = stringMap(pkg.scripts).start;
      const startFile =
        start && /^node\s+([\w./-]+\.m?js)(?:\s|$)/u.exec(start)?.[1];
      if (startFile && (await localFile(directory, startFile)))
        claims.push({
          kind: "entry",
          name: "start",
          text: `The start script enters at ${startFile}.`,
          basis: "code-observation",
          evidence: [
            {
              file: "package.json",
              line: propertyLine(packageSource, "start"),
            },
            { file: startFile, line: 1 },
          ],
        });
    } catch (error) {
      if (!(error instanceof SyntaxError)) throw error;
    }
  }

  let sawRoute = false;
  let sawScheduled = false;
  let routeEvidence: OnboardingStoryClaim["evidence"] = [];
  let scheduledEvidence: OnboardingStoryClaim["evidence"] = [];
  for (const finding of findings) {
    const data = object(finding.data);
    const evidence = finding.evidence.filter((item) => item.file).slice(0, 3);
    if (!evidence.length) continue;
    if (finding.kind === "application.route") {
      sawRoute = true;
      if (!routeEvidence.length) routeEvidence = evidence;
      const verb = string(data.verb);
      const path = string(data.path);
      const owner = string(data.controller);
      const method = string(data.method);
      if (!owner || !method) continue;
      claims.push({
        kind: "entry",
        name: `${owner}.${method}`,
        text: `${verb ?? "HTTP"} ${path ?? "route with unresolved path"} is declared on ${owner}.${method}.`,
        basis: "code-observation",
        evidence,
      });
      if (path?.includes("health"))
        claims.push({
          kind: "observation",
          text: `${verb ?? "HTTP"} ${path} is a declared health route; a live result is unverified.`,
          basis: "code-observation",
          evidence,
        });
    } else if (finding.kind === "scheduled-job") {
      sawScheduled = true;
      if (!scheduledEvidence.length) scheduledEvidence = evidence;
      const name = string(data.name);
      if (name)
        claims.push({
          kind: "entry",
          name,
          text: `${name} is registered as a scheduled entry.`,
          basis: "code-observation",
          evidence,
        });
    } else if (finding.kind === "messaging.consumer") {
      const handler = string(data.handler);
      if (handler)
        claims.push({
          kind: "entry",
          name: handler,
          text: `${handler} is declared as a message consumer.`,
          basis: "code-observation",
          evidence,
        });
    } else if (finding.kind === "integration") {
      const client = string(data.client);
      if (client)
        claims.push({
          kind: "boundary",
          name: client,
          text: `${client} is a declared integration dependency; calls and delivery are unverified.`,
          basis: "code-observation",
          evidence,
        });
    } else if (finding.kind === "database" || finding.kind === "messaging") {
      const technology = string(data.name);
      if (technology)
        claims.push({
          kind: "boundary",
          name: technology,
          text: `${technology} is declared as a ${finding.kind} dependency; runtime use is unverified.`,
          basis: "code-observation",
          evidence,
        });
    } else if (finding.kind === "setup.command") {
      const command = string(data.command);
      if (
        command &&
        data.generic !== "yes" &&
        /(?:test|start)/u.test(string(data.purpose) ?? "")
      )
        claims.push({
          kind: "observation",
          text: `${command} is declared or documented; it has not been executed.`,
          basis: "code-observation",
          evidence,
        });
    }
  }
  if (sawRoute) {
    claims.push({
      kind: "role",
      text: "This repository declares HTTP route handlers.",
      basis: "code-observation",
      evidence: routeEvidence,
    });
  }
  if (sawScheduled) {
    claims.push({
      kind: "role",
      text: "This repository declares scheduled work.",
      basis: "code-observation",
      evidence: scheduledEvidence,
    });
  }

  const incoming = new Map<string, number>();
  for (const entity of concepts.entities)
    for (const relation of entity.relations)
      incoming.set(relation.target, (incoming.get(relation.target) ?? 0) + 1);
  const centralEntities = [...concepts.entities]
    .sort(
      (left, right) =>
        (incoming.get(right.name) ?? 0) +
          right.relations.length -
          ((incoming.get(left.name) ?? 0) + left.relations.length) ||
        left.name.localeCompare(right.name),
    )
    .slice(0, 80);
  for (const entity of centralEntities) {
    claims.push({
      kind: "artifact",
      name: entity.name,
      text: `${entity.name} is a declared data entity; its business meaning is not established by the declaration alone.`,
      basis: "code-observation",
      evidence: [
        { file: entity.declaration.file, line: entity.declaration.line },
      ],
    });
  }
  const terms = centralEntities.map((entity) => {
    const relationEvidence = concepts.entities
      .flatMap((source) =>
        source.relations
          .filter((relation) => relation.target === entity.name)
          .map((relation) => ({
            file: relation.at.file,
            line: relation.at.line,
          })),
      )
      .slice(0, 8);
    const meaning = explicitMeaning(entity.name, paragraphs);
    return {
      name: entity.name,
      codeRole: "declared data entity",
      relationCount: entity.relations.length + (incoming.get(entity.name) ?? 0),
      relations: entity.relations.slice(0, 80).map((relation) => ({
        property: relation.property,
        target: relation.target,
        evidence: [{ file: relation.at.file, line: relation.at.line }],
      })),
      evidence: [
        { file: entity.declaration.file, line: entity.declaration.line },
        ...relationEvidence,
      ],
      ...(meaning ? { meaning } : {}),
    };
  });
  const limits: Record<OnboardingStoryClaim["kind"], number> = {
    purpose: 8,
    role: 6,
    entry: 80,
    artifact: 80,
    output: 12,
    boundary: 24,
    observation: 20,
  };
  const counts: Record<OnboardingStoryClaim["kind"], number> = {
    purpose: 0,
    role: 0,
    entry: 0,
    artifact: 0,
    output: 0,
    boundary: 0,
    observation: 0,
  };
  return {
    claims: claims.filter((claim) => counts[claim.kind]++ < limits[claim.kind]),
    terms,
    rejectedDescriptions,
  };
}

function projectParagraph(
  source: string,
): { text: string; line: number; endLine: number } | undefined {
  const lines = source.split(/\r?\n/u).slice(0, 80);
  let start = /^#\s/u.test(lines[0] ?? "") ? 1 : 0;
  const heading = lines.findIndex((line) =>
    /^#{1,3}\s+(?:about|overview|description|purpose)\b/iu.test(line),
  );
  if (heading >= 0) start = heading + 1;
  for (let index = start; index < Math.min(lines.length, start + 24); index++) {
    if (!lines[index]?.trim()) continue;
    if (/^\s*(?:#|[-*] |\||```)/u.test(lines[index]!)) break;
    const parts: string[] = [];
    const line = index + 1;
    for (; index < lines.length && parts.length < 6; index++) {
      const part = lines[index]!.trim();
      if (!part || /^\s*(?:#|[-*] |\||```)/u.test(part)) break;
      parts.push(part);
    }
    const text = parts
      .join(" ")
      .replace(/\[([^\]]+)\]\([^)]*\)/gu, "$1")
      .trim();
    return text.length >= 28 && text.length <= 500
      ? { text, line, endLine: line + parts.length - 1 }
      : undefined;
  }
  return undefined;
}

function explicitMeaning(
  name: string,
  paragraphs: readonly {
    text: string;
    file: string;
    line: number;
    endLine: number;
  }[],
): OnboardingStoryClaim | undefined {
  for (const paragraph of paragraphs) {
    const sentence = paragraph.text
      .split(/(?<=[.!?])\s+/u)
      .find((part) =>
        new RegExp(`\\b${name}\\s+(?:is|represents|means)\\b`, "iu").test(part),
      );
    if (sentence)
      return {
        kind: "artifact",
        name,
        text: sentence,
        basis: "repository-statement",
        evidence: Array.from(
          { length: paragraph.endLine - paragraph.line + 1 },
          (_, offset) => ({
            file: paragraph.file,
            line: paragraph.line + offset,
          }),
        ),
      };
  }
  return undefined;
}

async function optionalText(file: string): Promise<string | undefined> {
  try {
    if ((await stat(file)).size > 128_000) return undefined;
    return await readFile(file, "utf8");
  } catch (error) {
    if (isMissing(error)) return undefined;
    throw error;
  }
}

async function localFile(directory: string, file: string): Promise<boolean> {
  if (!/^[\w./-]+$/u.test(file) || file.startsWith("/") || file.includes(".."))
    return false;
  try {
    return (await stat(join(directory, file))).isFile();
  } catch (error) {
    if (isMissing(error)) return false;
    throw error;
  }
}

function propertyLine(source: string, key: string): number {
  const index = source
    .split(/\r?\n/u)
    .findIndex((line) => line.includes(JSON.stringify(key)));
  return index < 0 ? 1 : index + 1;
}

function stringMap(value: unknown): Record<string, string> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  return Object.fromEntries(
    Object.entries(value).filter((entry): entry is [string, string] =>
      entry.every((part) => typeof part === "string"),
    ),
  );
}

function object(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function string(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function isMissing(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}
