import { readFile, stat } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import type {
  Finding,
  OnboardingRepositoryNote,
  OnboardingTrace,
} from "@transferkit/core";

const unsafe =
  /(?:password|secret|api[_-]?key|private[_-]?key|token)\s*[:=]|-----BEGIN|process\.env\.[A-Z_]+\s*=/iu;
const generic =
  /(?:nest(?:js)? (?:framework|starter)|starter (?:repository|template)|boilerplate|generated by|welcome to)/iu;

export async function discoverOnboardingRepositoryNotes(
  directory: string,
  traces: readonly OnboardingTrace[],
  findings: readonly Finding[],
): Promise<OnboardingRepositoryNote[]> {
  const notes: OnboardingRepositoryNote[] = [];
  const readme = await optionalText(join(directory, "README.md"));
  if (readme) {
    const lines = readme.split(/\r?\n/u);
    const heading = lines.findIndex((line) =>
      /^#{1,3}\s+(?:description|about|overview)\b/iu.test(line),
    );
    const start =
      heading >= 0 ? heading + 1 : /^#\s+/u.test(lines[0] ?? "") ? 1 : 0;
    const paragraph: string[] = [];
    let paragraphLine = start + 1;
    for (
      let index = start;
      index < Math.min(lines.length, start + 12);
      index++
    ) {
      const line = lines[index]!.trim();
      if (/^#|^```|^[-*] |^\|/u.test(line)) break;
      if (!line) {
        if (paragraph.length) break;
        else continue;
      }
      if (!paragraph.length) paragraphLine = index + 1;
      paragraph.push(line);
    }
    const text = paragraph.join(" ").replace(/\[([^\]]+)\]\([^)]*\)/gu, "$1");
    if (
      text.length >= 30 &&
      text.length <= 350 &&
      !generic.test(text) &&
      !unsafe.test(text)
    )
      notes.push({
        kind: "description",
        text,
        file: "README.md",
        line: paragraphLine,
      });
  }
  const packageText = await optionalText(join(directory, "package.json"));
  if (packageText) {
    try {
      const pkg = JSON.parse(packageText) as { scripts?: { start?: unknown } };
      const start = pkg.scripts?.start;
      const entry =
        typeof start === "string"
          ? /^node\s+((?:[\w-]+\/)*[\w.-]+\.m?js)$/u.exec(start)?.[1]
          : undefined;
      if (
        entry &&
        !entry.includes("..") &&
        (await exists(join(directory, entry)))
      )
        notes.push({
          kind: "entry",
          text: `The declared start script points to ${entry}.`,
          file: entry,
          line: 1,
        });
    } catch (error) {
      if (!(error instanceof SyntaxError)) throw error;
    }
  }
  const sourceCache = new Map<string, string[] | undefined>();
  for (const trace of traces) {
    for (const method of trace.methods.slice(0, 8)) {
      const file = method.declaration.file;
      if (!sourceCache.has(file)) {
        const source = await optionalText(join(directory, file));
        sourceCache.set(file, source?.split(/\r?\n/u));
      }
      const lines = sourceCache.get(file);
      if (!lines) continue;
      const begin = Math.max(0, method.declaration.line - 5);
      const end = Math.min(
        lines.length,
        method.declaration.endLine,
        method.declaration.line + 100,
      );
      let count = 0;
      for (let index = begin; index < end && count < 2; index++) {
        const match = /^\s*(?:\/\/|\*|\/\*\*?)\s*(.+?)\s*(?:\*\/)?\s*$/u.exec(
          lines[index] ?? "",
        );
        if (!match) continue;
        const firstLine = index + 1;
        const parts = [match[1]!.trim()];
        while (index + 1 < end && parts.length < 4) {
          if (/[.!?]$/u.test(parts.at(-1) ?? "")) break;
          const following = /^\s*\/\/\s*(.+)$/u.exec(lines[index + 1] ?? "");
          if (!following || parts.join(" ").length + following[1]!.length > 300)
            break;
          parts.push(following[1]!.trim());
          index++;
        }
        const text = parts.join(" ").split(/(?<=[.!?])\s+(?=[A-Z`])/u)[0]!;
        if (
          text.length < 28 ||
          text.length > 300 ||
          unsafe.test(text) ||
          /\b(?:otp|password|secret|token|api[_-]?key)\b|[;{}=<>]|:contentReference|^\s*[\w.]+\s*:|\b(?:const|return|throw|if)\s*\(/iu.test(
            text,
          ) ||
          /^@|^TODO\b|^eslint|^ts-/iu.test(text)
        )
          continue;
        notes.push({
          kind: "comment",
          text,
          file,
          line: firstLine,
          journey: trace.entry.symbol,
        });
        count++;
      }
    }
    const seen = new Set<string>();
    for (const method of trace.methods.slice(0, 6)) {
      const file = method.declaration.file;
      const stem = basename(file).replace(/\.[jt]sx?$/iu, "");
      for (const suffix of ["spec.ts", "test.ts", "spec.js", "test.js"]) {
        const sibling = join(dirname(file), `${stem}.${suffix}`);
        if (seen.has(sibling) || !(await exists(join(directory, sibling))))
          continue;
        seen.add(sibling);
        notes.push({
          kind: "test",
          text: `Nearby test file for ${method.symbol}; its assertions have not been evaluated here.`,
          file: sibling,
          line: 1,
          journey: trace.entry.symbol,
        });
      }
    }
  }
  const entities = new Set(
    traces
      .flatMap((trace) =>
        trace.methods.map((method) =>
          method.symbol
            .split(".")[0]!
            .replace(/(?:Service|Repository)$/u, "")
            .toLowerCase(),
        ),
      )
      .filter((name) => name.length >= 5),
  );
  for (const finding of findings.filter(
    (item) => item.kind === "database.migration",
  )) {
    if (notes.filter((note) => note.kind === "migration").length >= 3) break;
    const file = finding.evidence[0]?.file;
    if (
      !file ||
      ![...entities].some((name) => file.toLowerCase().includes(name))
    )
      continue;
    notes.push({
      kind: "migration",
      text: "Migration file name matches a selected source owner; inspect its contents before treating it as related behavior.",
      file,
      line: 1,
    });
  }
  return notes.slice(0, 24);
}

async function optionalText(file: string): Promise<string | undefined> {
  try {
    if ((await stat(file)).size > 128_000) return undefined;
    return await readFile(file, "utf8");
  } catch (error) {
    if (isMissing(error)) return undefined;
    throw error;
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    return (await stat(file)).isFile();
  } catch (error) {
    if (isMissing(error)) return false;
    throw error;
  }
}

function isMissing(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}
